### ISSUE TITLE
Cambiar TXT del HOME

### ISSUE THREAD

**Issue by DonPowa** [DemocraciaEnRed/redinnovacionpolitica.org#1]
-PONER FRASE :  ‘’Nos une el sueño de una democracia de comunes, una democracia que redistribuya el poder” (en reemplazo de somos latinoamericanas y latinoamericanos//

-SACAR:  la fecha.

**Comment by fvilledary** [comment]
Arreglado

**Comment by ghost** [comment]
Se pueden ir viendo los cambios en algún lado?

**Comment by fvilledary** [comment]
@sebafer  http://democraciaenred.org/redinnovacionpolitica.org/
