### ISSUE TITLE
PARTICIPANTES

### ISSUE THREAD

**Issue by DonPowa** [DemocraciaEnRed/redinnovacionpolitica.org#2]
- [x] Poner los ''participantes'' en orden random.
- [x] Modificar la bio de Don Powa: ‘’Se especializa en  sustentabilidad, nuevas  tecnologías y participación ciudadana. Es co fundador de la Asociación Civil Amartya, de Implicate.org y del Partido de la Red. Actualmente se desempeña como director del centro de estudios en sustentabilidad Quinta Esencia ‘’ (la achique, no entraba).
- [ ] Poner los links a (tw, face, bla bla). Las necesitas?

**Comment by mjlescano** [comment]
Si, los necesitamos

**Comment by fvilledary** [comment]
Pareciera que sólo tienen facebook @DonPowa
